version: '2'
services:
  discovery-server:
    build: discovery-server/.
    ports:
      - "3000:3000"
  notification-service:
    build: notification-service/.
    ports:
    - "5555:5555"
    depends_on:
      - discovery-server
  telegram-bot:
    build: telegram-bot/.
    ports:
      - "8189:8189"
    depends_on:
      - discovery-server
