package ru.pankov.telegrambot.common;

public enum MessageType {
    START, HELP,
    ADD,
    ADD_BIRTHDAY_NAME, ADD_BIRTHDAY_DATE, CREATE_BIRTHDAY,
    ADD_EVENT_NAME, ADD_EVENT_DATE, ADD_EVENT_HOURS, ADD_EVENT_MINUTES, ADD_PERIOD, CREATE_EVENT,
    GET,
    DELETE_LIST, DELETE_CONFIRM, DELETE,
    RETURN, UNSUPPORTED
}
