package ru.pankov.telegrambot.common;

public enum UserSessionStage {
    MAIN_STAGE,
    ADD_STAGE,
    ADD_BIRTHDAY_NAME_STAGE, ADD_BIRTHDAY_DATE_STAGE,
    ADD_EVENT_NAME_STAGE, ADD_EVENT_DATE_STAGE, ADD_EVENT_HOURS_STAGE, ADD_EVENT_MINUTES_STAGE, ADD_PERIOD_STAGE,
    GET_STAGE,
    DELETE_LIST_STAGE, DELETE_CONFIRM_STAGE
}
