server:
  port: 8189
  servlet:
    context-path: /notification-bot

spring:
  datasource:
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: ${h2.username}
    password: ${h2.password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: notification-bot

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${host}:3000/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

