server:
  port: 8189
  servlet:
    context-path: /

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    #password: ${REDIS_PW}
    timeout: 60000

