name: deploy notification-service

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: Create secret
        uses: 1arp/create-a-file-action@0.2
        with:
          path: 'notification-service/src/main/resources/'
          file: '${{ secrets.NOTIFICATION_SERVICE_SECRET_NAME }}'
          content: |
            ${{ secrets.NOTIFICATION_SERVICE_SECRET_VALUE }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: notification-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/notification-service:latest

      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker ps | grep "mxpnk/notification-service" | awk '{ print $1 }' | xargs docker stop
            docker ps -a | grep "mxpnk/notification-service" | awk '{ print $1 }' | xargs docker container rm
            docker image ls | grep "mxpnk/notification-service" | awk '{ print $3 }' | xargs docker rmi
            docker pull mxpnk/notification-service
            docker run -d -p 8080:8080 mxpnk/notification-service
            docker logout
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          user: root
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
